### ISSUE TITLE
Fix button background

### ISSUE THREAD

**Issue by ChristianBingman** [acm-uic/flourish-2023#103]
Buttons don’t seem to have a drop shadow according to the Figma design

DoD:
- Buttons have a drop shadow consistent with the Figma design

Note: Figma allows you to inspect elements and it will give you exact details on the button shadow.

**Comment by kaodik** [comment]
Hey Chris, From what I understand a global css that applies the shadow box is all that is required correct?

**Comment by ChristianBingman** [comment]
The styling for this is in the PrimaryButton component. Check out the figma design to see what it is supposed to look like
