### ISSUE TITLE
Add speakers section to About Us

### ISSUE THREAD

**Issue by ChristianBingman** [acm-uic/flourish-2023#53]
Create the speakers section of the About Us page

DoD:
- There is a centered "Speaker" header 1 with proper styling
- There are 5 rounded pictures (see #51) with proper spacing (~0.5rem to start, follow the figma guide)
- The placeholder images are attached to the issue
- It should properly flow onto multiple lines and go down to a single line on mobile

**Comment by ChristianBingman** [comment]
![image](https://user-images.githubusercontent.com/42191425/195488298-b472212b-992a-40f1-aa36-91e3c51da4f2.png)
![image](https://user-images.githubusercontent.com/42191425/195488322-23d86cc8-fedf-4c57-94df-51ddde8e6db1.png)
![image](https://user-images.githubusercontent.com/42191425/195488337-fd6ae64f-aa44-4d1a-83db-0883f0cd5228.png)
![image](https://user-images.githubusercontent.com/42191425/195488359-bfec2221-5372-4891-879a-eba7d6591692.png)
![image](https://user-images.githubusercontent.com/42191425/195488370-c4a57052-1743-4a9b-b819-7a489ca9e601.png)

**Comment by rapterjet2004** [comment]
Hey Christian, do you want me to create an assets folder for these placeholder images and use the local path, or to just use the online url path instead?

**Comment by ChristianBingman** [comment]
Closing manually
