### ISSUE TITLE
Create the day selector for the event schedule for mobile

### ISSUE THREAD

**Issue by ChristianBingman** [acm-uic/flourish-2023#70]
Create the mobile day selector for the event schedule

DoD:
- Track selection between each day and dynamically update the listed events (check react use state)
- No animations should be added at this stage
- Uses proper sizing and coloring (background, text color changes)
- Should fill the width of the screen

Note: Check figma designs for font sizings, you should use what is provided to you in the global css as much as possible. This might be a bit complicated, but it is a great practice for responsive design.

**Comment by ThatMarko** [comment]
I was literally waiting for this to be finished before I start working on #72 
I'll get 'em both done over the weekend.
