### ISSUE TITLE
Open maps on event tap (mobile)

### ISSUE THREAD

**Issue by ChristianBingman** [acm-uic/flourish-2023#72]
When the user taps on an event on mobile, it should take them to their maps application with the location of the event.

DoD:
- When the user clicks the event, open a location in maps
- It should open in their default application/prompt for it

Note: This will require some research, maybe even a custom library that handles this

**Comment by ThatMarko** [comment]
The question is how do we store event locations @ChristianBingman? We'd need coordinates on the map or just an address as a string. I will try working on this for the next few days.

Sources: 
https://stackoverflow.com/questions/10204612/open-google-maps-from-hyperlink
https://en.wikipedia.org/wiki/Geo_URI_scheme
https://www.iana.org/assignments/uri-schemes/prov/maps
https://stackoverflow.com/questions/10769631/is-there-a-map-uri-prefix-to-launch-map-application-like-mailto-or-tel

**Comment by ChristianBingman** [comment]
Yeah so I believe the desktop version we are currently using lat&long, so for now we can keep this as convention.
